Make use of PC stac collection to pull CMIP6 paths
os-climate/hazard pull request #38
Opened 2024-03-28 18:24 UTC by emileten

This is a draft PR. Comments welcome @joemoorhouse !

This PR: 

- Creates a small function to do a stac search based on a catalog url and search parameters provided as inputs. Returns a collection of items. 
- In the nasa cmip6 hazard class, swaps out the AWS S3 path logic in the `path` function for a call to the above STAC utility to retrieve the paths from the STAC metadata. 

This code is not yet tested nor linted.

2024-03-29 15:34 UTC, joemoorhouse commented
Hi @emileten,

Thanks for this. I've just made some changes to make hazard a healthier environment to develop in :) (and align us with the Linux Foundation standards):
- move to pdm and pyproject.toml
- restructure; in particular test -> tests and moves to the standard's location
- add checks (mypy, isort, black, flake8)
- add tox.ini too run checks
- add GitHub action to run tox as check on PR

The code changes (a lot of reformatting!) are pushed and I'm just making sure the CI/CD 'tox' step runs OK on GitHub for Python 3.8, then same for Python 3.10. Once that all works, I think you should be good to add your tests and lints (without risk of having to redo!).

Thanks,
Joe

2024-04-04 13:48 UTC, emileten commented
@joemoorhouse I just realized that workflows from my fork wait from approval from a maintainer. Can we change this so that my workflows run automatically to speed up the process? Maybe changing my status to maintainer. Thanks!

2024-04-12 20:00 UTC, sharkinsspatial requested changes

2024-04-17 15:56 UTC, ModeSevenIndustrialSolutions approved these changes
Looks good to go

2024-04-18 08:30 UTC, merged